add working RequstViewModelValidator
kacykvaa/orlik-api pull request #10
Opened 2021-01-18 19:58 UTC by kacykvaa

2021-01-21 18:00 UTC, kacykvaa commented on src/Common/UI/Request/Validator/Constraints/UniqueFacilityNameValidator.php
> +        if (null === $value || '' === $value) return;
Dodałem te if'y zgodnie z tym co znalazłem na symfony. Mają być czy je usunąć?

2021-01-23 13:03 UTC, mtanasiewicz requested changes

2021-01-23 13:03 UTC, mtanasiewicz commented on src/UI/Model/Request/Facility.php
> +     * @Assert\Length(min=5)
A co jak ktoś nazwie swój klub sportowy `AS` :) ?

2021-01-23 13:03 UTC, mtanasiewicz commented on src/UI/Model/Request/Facility.php
> +     * @AcmeAssert\UniqueFacilityName()
Czy nazwa klubu sportowego na pewno powinna być unikalna? To nie założymy dwóch klubów sportowych o nazwie `Promyczek` w Polsce? :) I coś tu nie tak jest z namespacem, skąd się wziął `AcmeAssert` ? Przypadkiem nie żywcem skopiowany z dokumentacji? :)

2021-01-25 19:19 UTC, mtanasiewicz approved these changes
good job!

2021-01-25 19:20 UTC, merged