Future/facility
kacykvaa/orlik-api pull request #3
Opened 2020-11-22 12:20 UTC by kacykvaa

2020-11-22 12:52 UTC, mtanasiewicz requested changes

2020-11-22 12:52 UTC, mtanasiewicz commented on migrations/Version20201121164337.php
> +final class Version20201121164337 extends AbstractMigration
Wszystkie migracje z jednego nowego ficzera powinny być w jednej migracji a nie w kilku.

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Controller/CreateFacilityAction.php
> +
Zbędna dodatkowa linia

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Controller/CreateFacilityAction.php
> +        return new JsonResponse('Saved Facility: '.$jsonContent);
ten string 'Saved Facility: ' jest kompletnie niepotrzeny i psuje jsona. Jak ktoś odbierając to na froncie będzie chciał zrobić json_decode to mu walnie błędem. Zwracamy tylko jsona. Nie widzę też statusu HTTP ustwionego na HTTP_CREATED, JsonResponse defaultowo zwraca HTTP_OK.

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Controller/CreateFacilityAction.php
> +        $orlik1->setName("szkoła");
Coś nam tutaj chyba nie zagrało :D. Tworzysz orlik, ale miałeś go stwrzyć z tego co ktoś przesłał jsonem, a nie hardkodować dane w seterach. W ten sposób ten endpoint jest bezużyteczny, bo jak stworzysz orlik nr 2 o parametrze name=legia?

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Controller/CreateFacilityAction.php
> +        $orlik1 = new Facility();
Niepotrzebnie nazwałeś zmienną jako orlik1. Tworzymy tylko 1 orlik więc może się nazywać orlik. Natomiast tutaj nie tworzymy orlika, tylko facility więc tak na prawdę zmienna powinna się nazywać $facility.

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Address.php
> +    public function setStreet(string $street): self
Klasy, a zwłaszcza encje doctrinowe nie powinny mieć setterów. Zamiast tego powinny mieć wszystkie wymagane do utworzenia dane, pakowane przez konstruktor. W ten sposób tworząc dany obiekt inny programista nigdy nie zapomni wykonać jakiegoś settera. Jedynie relacje powinny zostać osobno poprzez setery i addery. Tutaj ładnie przez konstruktor zrobiłeś wsadzenie danych, ale niepotrzebnie te settery udostępniłeś

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Facility.php
> +    public function __construct()
Name i pitchTypes powinny wejść przez konstruktor. Address również, ponieważ jest to realcja OneToOne, czyli bez jednego nie da się stworzyć drugiego(nullabe=false)

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Facility.php
> +     * @ORM\JoinColumn(nullable=false)
ta relacja powinna być w odwrotną stronę, czyli JoinColumn powinien być po stronie adresu. Facility jest naszym głównym obiektem, który będzie rozdrzewiał się dalej. Jeżeli zapakujemy do niego idki wszystkich zależnych obiektów, to strasznie spuchnie i nie będzie się dało z tym pracować. A jeżeli umieścisz id w obiektach zależnych, to wtedy każdy wie o facility przechowując jego id, a tabela facility nie jest ogromna.

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Images.php
> +class Images
class Image. Klasa jest zawsze reprezentacją jednego obiektu, chyba że jest to kolekcja (np ArrayCollection) które przechwouje w sobie wiele obiektów tej samej klasy.

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Images.php
> +
jakieś 2 linie dodatkowe się wkradły

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Images.php
> +    public function __construct(string $filename, string $path)
w konstruktorze brakuje $facility. Bez niego nie utworzymy encji Image

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Images.php
> +    public function setPath(string $path): self
settery do wywalenia

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Repository/AdressRepository.php
> +    public function findByExampleField($value)
nie zostawiamy zakomentowanego kodu, nigdy i nigdzie :)

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Repository/FacilityRepository.php
> +        return $this->createQueryBuilder('f')
komentarze out

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Repository/ImagesRepository.php
> +            ->orderBy('i.id', 'ASC')
jw

2020-11-22 12:52 UTC, mtanasiewicz commented on templates/create_facility_action/index.html.twig
> +{% block title %}Hello CreateFacilityActionController!{% endblock %}
A cotto? Miało nie być twiga :)

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Repository/ImagesRepository.php
> +class ImagesRepository extends ServiceEntityRepository
ImageRepository

2020-11-22 12:52 UTC, mtanasiewicz commented on src/Entity/Facility.php
> +    public function setPitchTypes(array $pitchTypes): self
wszystkie settery out

2020-11-22 12:52 UTC, mtanasiewicz commented on src/DataFixtures/FacilityFixtures.php
> +    {
Pusta klasa, która nic nie robi? Nie wolno takich rzeczy robić :)

2020-11-22 13:15 UTC, mtanasiewicz commented on src/Entity/Address.php
> +    private $id;
We wszystkich klasach, które przechowują dane, brakuje typowania propertiesów wprowadzonego w php 7.4. Powinno być:

private int $id;
private string $street;

itp.

2020-11-23 09:12 UTC, mtanasiewicz commented on config/packages/lexik_jwt_authentication.yaml
> +    token_ttl: 7200
dobrze byłoby dodać zmienną do .env o nazwie JWT_TOKEN_TTL i z niej korzystać, żeby przestawienie tej wartości nie wymagało commita w kodzie.

2020-11-23 09:15 UTC, mtanasiewicz commented on src/Entity/Address.php
> +    private $id;
https://stitcher.io/blog/typed-properties-in-php-74 Tutaj jest dobry artykuł o tym ficzerku

2020-11-23 09:15 UTC, mtanasiewicz commented on src/Repository/ImageRepository.php
> +            ->andWhere('i.exampleField = :val')
komentarze out

2020-11-26 09:21 UTC, mtanasiewicz requested changes

2020-11-26 09:21 UTC, mtanasiewicz commented on migrations/Version20201124172045.php
> +<?php
Znowu mamy 2 migracje, a mieliśmy mieć  jedną :) Najlepiej je usunąć dopóki nie skończymy ficzera i wygenerować całość na końcu. Do tego czasu możesz pracować z doctrine:schema:update --force, na końcu wywalić bazę, stworzyć nową i wygenerować migrację jeszcze raz.

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Controller/CreateFacilityAction.php
> +        $facility = new Facility('Gimnazjum',['Football', 'Basketball'],
Brakuje przyjęcia danych wchodzących jsonem.

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Entity/Address.php
> +     * @ORM\Column(type="string", length=255)
length w postcode wystarczy ustawić na 20 znaków, oszczędzi to pamieć w bazie.

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Entity/Address.php
> +     * @ORM\Column(type="string", length=255)
streetNumber można ustawić na 40 znaków

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Entity/Address.php
> +    public function getId(): ?int
z geterów wyrzuć proszę słówko get, dzisiaj się już tak nie robi :)

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Entity/Facility.php
> +            if ($image->getFacility() === $this) {
Tutaj ustawiasz w Image facility na null, ale w tej klasie relacja do facility nie jest nullable. Jeżeli użyjesz tej metody i zrobisz flush, bez usunięcia obrazka z bazy, Doctrine sypnie wyjątkiem. Prawidłowo powinniśmy usuwać obrazek z bazy i jedynie wyrzucać go z kolekcji. W jakimś serwisie wyglądałoby to tak:

```
class Facility {
//...
public function removeImage(Image $image): void {
    if($this->images->contains($image) {
        $this->images->removeElement($image);
    }
}

i gdzieś w kodzie:

$em->remove($image);
$facility->remove($image);
```

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Entity/Image.php
> +
zawsze jedna linia odstępu między metodami

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Entity/Image.php
> +    public function setFilename(string $filename): self
settery do wyrzucenia

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Repository/AdressRepository.php
> +    public function findByExampleField($value)
Tutaj chodziło mi o to, żebyś te metody usunął, one nic nie robią i są to tylko przyklady.

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Repository/FacilityRepository.php
> +        return $this->createQueryBuilder('f')
jw.

2020-11-26 09:21 UTC, mtanasiewicz commented on src/Repository/ImageRepository.php
> +            ->andWhere('i.exampleField = :val')
jw

2020-11-26 18:44 UTC, kacykvaa commented on src/Entity/Address.php
> +    public function getId(): ?int
wszędzie poprawić?

2020-12-11 16:18 UTC, closed without merging