Feature/update facility
kacykvaa/orlik-api pull request #8
Opened 2021-01-04 14:07 UTC by kacykvaa

2021-01-06 13:52 UTC, mtanasiewicz requested changes
good job ogólnie

2021-01-06 13:52 UTC, mtanasiewicz commented on src/Application/Entity/Address.php
> +    public function updateStreetNumber($streetNumber): void
behaviour powinien być jedną metodą, która zaktualizuje wszystkie dane, które da się aktualizować w tym ficzerze. To co tutaj zrobiłeś to tak jakbyś miał settery, co jest anemiczne i niedobre bo nie widać w tym żadnej funkcjonalności.

2021-01-06 13:52 UTC, mtanasiewicz commented on src/UI/Controller/UpdateFacilityAction.php
> +        $facility = $this->facilityRepository->getById($id);
Brakuje nam tutaj obsłużenia wyjątku, w którym FacilityRepository nie znajdzie facility o danym id i wyrzuci ResourceNotFoundException

2021-01-06 13:52 UTC, mtanasiewicz commented on src/UI/Controller/UpdateFacilityAction.php
> +
wkradła się linia odstępu, która jest niepotrzebna. Zawsze robimy odstepy po jednej linii pomiędzy blokami kodu

2021-01-13 20:57 UTC, mtanasiewicz requested changes

2021-01-13 20:57 UTC, mtanasiewicz commented on src/Application/Repository/AddressRepository.php
> +            throw new DuplicateEntityException('Address already exists');
Asercji nie powinno się robić w repozytoriach, ponieważ łamiesz zasadę Single Responsibility Principle:
https://pl.wikipedia.org/wiki/Zasada_jednej_odpowiedzialno%C5%9Bci

Powinieneś nazwać tą metodę np `countAddressesByStreetNumberAndZip`, zrobić dodatkową klasę `FacilityAddressValidator` która z tego repo skorzysta, wyjmie ilość tych adresów z repo, sprawdzi czy jest więcej niż 0 i tam rzuci wyjątek.

2021-01-13 20:57 UTC, mtanasiewicz commented on src/Application/Repository/FacilityRepository.php
> +    public function assertFacilityNameDoesNotExist(string $name)
Paczaj wyżej

2021-01-13 20:57 UTC, mtanasiewicz commented on src/UI/Controller/UpdateAddressAction.php
> +            $address->updateAddress(
metoda w $address powinna się nazywać `updateData`

2021-01-13 20:57 UTC, mtanasiewicz commented on src/UI/Controller/UpdateFacilityAction.php
> +            $facility->updateFacility($facilityRequest->name, $facilityRequest->pitchTypes);
rozdziel proszę to `updateFacility` na `updateName` oraz `updatePitchTypes`

2021-01-13 20:57 UTC, mtanasiewicz commented on src/UI/Model/Response/Factory/AddressViewModelFactory.php
> +
zarówno pomiędzy `declare(strict_types=1);` a `namespacem` jak i pomiędzy `namespacem` a `usami`. Poczytaj sobie po PSR2 https://www.php-fig.org/psr/psr-2/

2021-01-13 20:57 UTC, mtanasiewicz commented on src/UI/Model/Response/Factory/FacilityViewModelFactory.php
> +
Jak wyżej

2021-01-13 20:57 UTC, mtanasiewicz commented
Wprowadzisz te zmiany wszędzie i możesz mergować

2021-01-14 22:21 UTC, kacykvaa commented
add working updateFacilityAction and updateAddressAction

2021-01-14 22:21 UTC, merged